spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank cards related prodA APIs "
  contactDetails:
    name: "prod prod - Developer"
    email: "prod@eazybank.com"
  onCallSupport:
    - (555) 1111-1234
    - (555) 1111-1345